### ISSUE TITLE
Says it depends on git, but really uses libgit2

### ISSUE THREAD

**Issue by sgraf812** [SrTobi/speed-collector#1]
In INSTALL.md, it says that speed-collector needs git installed, when really it uses nodegit and libgit2 by extension.

**Comment by SrTobi** [comment]
Yeah, but you need git to follow the install.md :smile: https://github.com/nodegit/nodegit says that nodegit does not need any native dependencies. Is that incorrect or did you need to install something to run this?

**Comment by sgraf812** [comment]
Ah, OK. I'm not sure, because I had the ubtuntu package for `libgit2` installed on the machine I was running it on.
